### PR TITLE
review_checklist

### PR DESCRIPTION
**Pull request by JarbasAl**
this is intended as a conversation starter

Review Checklist:
- does the skill.json contain a valid github release
- if `desktop_file` is True, does the skill implement a valid homescreen
- are the `tags` accurate
- is the license acceptable
- is the skill appropriate (no adult content, no malware)

### CODE REVIEW

**Comment by ChanceNCounter** [comment]
We need to word that thing about the git release with a couple points in mind:

* `branch` param not required if the tag is in the URL
* URL or `branch` may refer to a working branch during skill development and review, but *must* refer to a tag in the published/merged version
* you don't *have* to host your skills on GitHub as long as your git host allows linking to tags

**Comment by JarbasAl** [comment]
right now OSM is tightly coupled to github

**Comment by NeonDaniel** [comment]
I would prefer to just write a  script to validate the json, check license, check repo, and check release. For now, tags, appropriate content and malware checks would have to be manual review. I agree with the points though.


There might be some malware checking action out there, though might be better left to manual review to also see if the skill works as intended, meets content standards, etc.. In the future, it would be nice to have some standard test action that could be used to unit test skills (think: run every method with an intent handler with some mock data).

**Comment by JarbasAl** [comment]
my idea is to not have a list of acceptable things, only a list of unacceptable things that are easy to check

one of the issues with official mycroft marketplace is that the review process is SLOW and it imposes a lot of work on skill devs, i dont submit my skills there because it ends up being more work than the actual coding of the skills, it just ain't fun... i want to avoid that here

**Comment by JarbasAl** [comment]
i like writing a script, that leaves us with checking tags, homescreen and that it isnt malware/porn. all things super easy to validate

we dont test that the skill works, we test that it integrates with OSM properly only

**Comment by NeonDaniel** [comment]
How is a homescreen validated? Could this be automated too?

At some point, it might be nice to validate functionality and blacklists (or provide a way for skill authors to), but definitely out of scope for this

**Comment by ChanceNCounter** [comment]
I was thinking about that last night. It's tricky. We might be able to run BigScreen in a container, but we'd still need a way to hook in and validate that the homescreen both launched and contained working elements.

I don't know that it can be reviewed automatically.

**Comment by JarbasAl** [comment]
for youtube skill from aix that would be checking these 2 lines

https://github.com/AIIX/youtube-skill/blob/master/__init__.py#L64
https://github.com/AIIX/youtube-skill/blob/master/res/desktop/youtube-skill.desktop#L8

**Comment by NeonDaniel** [comment]
> for youtube skill from aix that would be checking these 2 lines
> 
> https://github.com/AIIX/youtube-skill/blob/master/__init__.py#L64
> https://github.com/AIIX/youtube-skill/blob/master/res/desktop/youtube-skill.desktop#L8

Looks like automated string comparison to me

**Comment by ChanceNCounter** [comment]
I wouldn't trust string comparison to check for evil.

**Comment by NeonDaniel** [comment]
> I was thinking about that last night. It's tricky. We might be able to run BigScreen in a container, but we'd still need a way to hook in and validate that the homescreen both launched and contained working elements.
> 
> I don't know that it can be reviewed automatically.

I think this would be a big project; you can probably setup a self-hosted testrunner with BigScreen and OVOS installed and hook into it, look for logs or messagebus events.. Similar to how Mycroft does their skills integration testing.

**Comment by ChanceNCounter** [comment]
To be clear, with respect to evil, I'm referring mainly to the desktop entry. It doesn't just have to be a valid command, we have to make sure it's actually launching a GUI, and not taking advantage of the specs to run a nasty shell script or etc.

The contents of the code are code review's problem.

**Comment by NeonDaniel** [comment]
> I wouldn't trust string comparison to check for evil.

If it should always launch mycroft-gui-app with a '--skill' param, I think string comparison is as good or better than human.. With any of these, if it doesn't pass some test, a human would be doing some sanity check..

**Comment by ChanceNCounter** [comment]
> If it should always launch mycroft-gui-app with a '--skill' param, I think string comparison is as good or better than human

afaik the .desktop spec doesn't require `open` commands to sanitize 'injection' because sometimes you really do want a semicolon

I might be misremembering, but I'm pretty sure.

**Comment by JarbasAl** [comment]
in this case the desktop files should accept this specific launch command only, even detecting a single extra space should throw a warning, so its pretty safe to script this out. It's a bit harder to inspect the init.py but also doable

**Comment by ChanceNCounter** [comment]
but what if the GUI skill really does want a semicolon? maybe it has to launch a daemon. that would be a convenient place

**Comment by NeonDaniel** [comment]
> but what if the GUI skill really does want a semicolon? maybe it has to launch a daemon. that would be a convenient place

I think 90% of skills would be copy/pasted Exec lines like that example anyways; the 10% exceptions would just show a failure that a human has to review.. We could also get fancier with some regex matching to allow known good templates, but that can get dangerous too

**Comment by AIIX** [comment]
> but what if the GUI skill really does want a semicolon? maybe it has to launch a daemon. that would be a convenient place

as far as I know semicolon are not valid the gui does not want any semicolons, the homescreen event is not only called by .desktop files but is also used in trigger events within skills and that needs to be valid string entries, I do not believe one can have example-skill.author.home;

**Comment by AIIX** [comment]
For homescreen launching from .desktop skill_id/skill_namespace/skill_folder.author.home is enforced, where skill_id/skill_namespace should == skill_folder or it does not work, i understand its a bit to tightly coupled but its the only way for GUI to be able to know which skill is actually being requested to show up

**Comment by JarbasAl** [comment]
as for the skill name, OSM respects the `repo.author` == `folder_name` paradigm on install, so does `msm`, so the gui can rely on that

the point of the review is to ensure the .desktop is valid, in particular for bigscreen since thats where it started, but by setting this standard for every skill any distro can benefit from it

would be great if you could document, maybe a bullet point list, things needed in a way skill devs understand

**Comment by JarbasAl** [comment]
checking that the .desktop message is `repo.author.homescreen` makes everything so much easier, why isnt  this in the MycroftSkill class to begin with?

**Comment by NeonDaniel** [comment]
> For homescreen launching from .desktop skill_id/skill_namespace/skill_folder.author.home is enforced, where skill_id/skill_namespace should == skill_folder or it does not work, i understand its a bit to tightly coupled but its the only way for GUI to be able to know which skill is actually being requested to show up
> 
> Mycroft-GUI is not connected to the bus before being launched.. we need to actively blacklist and whitelist skills based in this tight coupling so when data over the message bus starts flowing we know the exact target that its coming from, also if you do try putting anything in --skill other than the required parameter it hits https://github.com/MycroftAI/mycroft-gui/blob/master/application/main.cpp#L118 where its hits the activeSkills.whiteList, the only thing that will happen is all the string value just gets added to the whitelist and break current gui session, since if its anything other than the expected input, so basically nothing else happens, should be safe from any case of command execution

Would it be safe then (for now) to assume that a skill .desktop file has an exec line like:

`Exec=mycroft-gui-app .* --skill={skill_dirname}.{author}.*`?

**Comment by AIIX** [comment]
> > For homescreen launching from .desktop skill_id/skill_namespace/skill_folder.author.home is enforced, where skill_id/skill_namespace should == skill_folder or it does not work, i understand its a bit to tightly coupled but its the only way for GUI to be able to know which skill is actually being requested to show up
> > Mycroft-GUI is not connected to the bus before being launched.. we need to actively blacklist and whitelist skills based in this tight coupling so when data over the message bus starts flowing we know the exact target that its coming from, also if you do try putting anything in --skill other than the required parameter it hits https://github.com/MycroftAI/mycroft-gui/blob/master/application/main.cpp#L118 where its hits the activeSkills.whiteList, the only thing that will happen is all the string value just gets added to the whitelist and break current gui session, since if its anything other than the expected input, so basically nothing else happens, should be safe from any case of command execution
> 
> Would it be safe then (for now) to assume that a skill .desktop file has an exec line like:
> 
> `Exec=mycroft-gui-app .* --skill={skill_dirname}.{author}.*`?

I don't think it should cause any harm but that string is illegal as per the parameters, if your doing a string check anyways would it not catch " .* --skill={skill_dirname}.{author}.*" failing since it has no match ?

**Comment by JarbasAl** [comment]
im taking note to enforce proper .desktop files in OSM also :+1:

**Comment by ChanceNCounter** [comment]
Could compare f-strings instead of regex, considering that the operative delimiter *before* `--skill...` is whitespace.

**Comment by JarbasAl** [comment]
just gonna leave this awesome tool here https://github.com/tfeldmann/simplematch

**Comment by NeonDaniel** [comment]
> Could compare f-strings instead of regex, considering that the operative delimiter _before_ `--skill...` is whitespace.

I guess the syntax was less the question as much as the concept for me


> just gonna leave this awesome tool here https://github.com/tfeldmann/simplematch

Looks pretty easy!

**Pull request closed without merging**
